<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5CII570" ignored="0" name="Test" tests="4" failures="2" timestamp="23 Apr 2020 09:33:01 GMT" time="13.064" errors="0">
  <testcase name="test" time="6.165" classname="Tst.NewTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Tst.NewTest.test(NewTest.java:31)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="7.876" classname="Tst.TestDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Tst.TestDemo.test(TestDemo.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test2" time="3.856" classname="Tst.NewTest"/>
  <testcase name="test2" time="5.081" classname="Tst.TestDemo"/>
</testsuite> <!-- Test -->
